name: Cypress Tests (Chrome Only)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Executa todos os dias às 2:00 UTC
    - cron: '0 2 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install additional dependencies
        run: |
          npm install --save-dev @faker-js/faker
          npm install --save-dev mochawesome
          npm install --save-dev mochawesome-merge

      - name: Verify site accessibility
        run: |
          curl -f https://automationexercise.com || exit 1
          echo "✅ Site is accessible"

      - name: Wait for site to be ready
        run: |
          sleep 10
          echo "⏳ Waiting for site to be fully ready..."

      - name: Verify Cypress installation
        run: |
          npx cypress verify
          npx cypress version

      - name: Run Cypress tests
        run: |
          npx cypress run --browser chrome --headless
        env:
          CYPRESS_RETRIES: 2
          CYPRESS_VIDEO: true
          CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true

      - name: Check test results
        run: |
          if [ -d "cypress/reports" ]; then
            echo "✅ Test reports generated successfully"
            ls -la cypress/reports/
          else
            echo "❌ No test reports found"
            exit 1
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-results-chrome
          path: |
            cypress/reports/
            cypress/videos/
            cypress/screenshots/

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos-chrome
          path: cypress/videos/

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots/

  # Job para gerar relatório consolidado
  generate-report:
    runs-on: ubuntu-latest
    needs: cypress-run
    if: always()
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: cypress-results-chrome
          path: artifacts

      - name: Merge reports
        run: |
          mkdir -p cypress/reports
          find artifacts -name "*.json" -exec cp {} cypress/reports/ \;
          npm run report:merge
          npm run report:generate

      - name: Upload consolidated report
        uses: actions/upload-artifact@v4
        with:
          name: consolidated-report
          path: cypress/reports/

  # Job para notificação (opcional)
  notify:
    runs-on: ubuntu-latest
    needs: [cypress-run, generate-report]
    if: always()
    
    steps:
      - name: Notify test results
        run: |
          if [ "${{ needs.cypress-run.result }}" == "success" ]; then
            echo "✅ All tests passed!"
          else
            echo "❌ Some tests failed!"
          fi

